### ISSUE TITLE
领地管理

### ISSUE THREAD

**Issue by yufengya0420** [LiteLScript-Dev/iLand-Core#25]
22:36:32 ERROR [LiteLoader] Fail in form callback!
22:36:32 ERROR [LiteLoader] In Plugin: iLand
22:36:32 ERROR [LiteLoader] [string "unknown.lua"]:3669: bad argument #2 to 'gsub' (string expected, got nil)
stack traceback:
[C]: in function 'string.gsub'
[string "unknown.lua"]:3669: in function 'string.gsubEx'
(...tail calls...)
[string "unknown.lua"]:2307: in field 'Information'
[string "unknown.lua"]:2024: in function <[string "unknown.lua"]:2020>

**Comment by Redbeanw44602** [comment]
请提供安装的插件版本和复现方法
